apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  selector:
    component: postgres-master
  type: NodePort
  ports:
    - name: postgres-master-port
      port: 5432
      targetPort: 5432
      nodePort: 30032
      protocol: TCP
