apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
  labels:
    component: postgres-master
spec:
  selector:
    matchLabels:
      component: postgres-master
  serviceName: postgres-master
  template:
    metadata:
      labels:
        component: postgres-master
    spec:
      containers:
        - name: postgres
          image: postgres:11
          command:
            [
                "sh",
                "-c",
                "docker-entrypoint.sh -c config_file=/var/config/postgresql.conf -c hba_file=/var/config/pg_hba.conf",
            ]
          # Readiness and Liveness Probe
          readinessProbe:
            exec:
              command: [ "psql", "-Upostgres", "-dpostgres", "-c", "SELECT 1" ]
            initialDelaySeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: [ "psql", "-Upostgres", "-dpostgres", "-c", "SELECT 1" ]
            initialDelaySeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-master-data
            - mountPath: /var/config
              name: postgres-master-configmap
      volumes:
        - name: postgres-master-configmap
          configMap:
            name: postgres-master-configmap
        - name: postgres-master-data
          persistentVolumeClaim:
            claimName: postgres-master-data-vol